In [4]:
import tensorflow as tf

# Agenda
- How TensorFlow Works
- Declaring Variables and Tensors
- Using Placeholders and Variables
- Working with Matrices
- Declaring Operations
- Implementing Activation Functions

# How TensorFlow Works
- Declaring Tensors
- Basic Unit of TensorFlow

# Fixed Tensors

In [5]:
zero_tsr = tf.zeros([4,5])

In [6]:
zero_tsr

<tf.Tensor 'zeros:0' shape=(4, 5) dtype=float32>

In [7]:
ones_tsr = tf.ones([6,7])

In [8]:
ones_tsr

<tf.Tensor 'ones:0' shape=(6, 7) dtype=float32>

In [11]:
filled_tsr = tf.fill([3,4], 99)

In [13]:
constant_tsr = tf.constant([1,2,3])

In [14]:
zero_similar = tf.zeros_like(constant_tsr)
zero_similar

<tf.Tensor 'zeros_like:0' shape=(3,) dtype=int32>

# Sequence Tensors

In [15]:
linear_tsr = tf.linspace(start=0.0, stop=1.0, num=3)

In [16]:
linear_tsr

<tf.Tensor 'LinSpace:0' shape=(3,) dtype=float32>

In [18]:
int_seq_tsr = tf.range(start=6, limit=15, delta=3)

In [19]:
int_seq_tsr

<tf.Tensor 'range:0' shape=(3,) dtype=int32>

In [20]:
# Random Tensors

In [21]:
rand_tsr = tf.random_uniform([3,4], minval=0, maxval=1)

In [23]:
rand_tsr

<tf.Tensor 'random_uniform:0' shape=(3, 4) dtype=float32>

In [24]:
tf.random_shuffle(rand_tsr)

<tf.Tensor 'RandomShuffle:0' shape=(3, 4) dtype=float32>

In [25]:
tf.random_crop(rand_tsr,[2,2])

Instructions for updating:
Colocations handled automatically by placer.


<tf.Tensor 'random_crop:0' shape=(2, 2) dtype=float32>

In [26]:
# USing Placeholders and Variables

In [27]:
my_var = tf.Variable(tf.zeros([2,3]))
# Tensor function takes as an input and outputs a variable

In [28]:
my_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref>

In [29]:
sess = tf.Session()

In [30]:
sess.run(ones_tsr)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [31]:
sess.run(zero_tsr)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [32]:
sess.run(filled_tsr)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [33]:
sess.run(int_seq_tsr)

array([ 6,  9, 12])

In [34]:
sess.run(constant_tsr)

array([1, 2, 3])

In [35]:
sess.run(zero_similar)

array([0, 0, 0])

In [36]:
sess.run(linear_tsr)

array([0. , 0.5, 1. ], dtype=float32)

In [37]:
sess.run(rand_tsr)

array([[0.3187108 , 0.5594566 , 0.6241174 , 0.09519148],
       [0.606647  , 0.48071826, 0.20965326, 0.10992861],
       [0.53638196, 0.7225375 , 0.406662  , 0.44454217]], dtype=float32)

In [39]:
a = sess.run(my_var.initializer)

In [45]:
tfops = tf.global_variables_initializer()

In [46]:
sess.run(tfops)

In [47]:
sess = tf.Session()

In [48]:
x = tf.placeholder(tf.float32, shape=[2,2])

In [50]:
y = tf.identity(x)

In [52]:
import numpy as np
x_vals = np.random.rand(2,2)

In [53]:
sess = tf.Session()

In [54]:
sess.run(y, feed_dict= {x:x_vals})

array([[0.63709354, 0.2828726 ],
       [0.4647039 , 0.37693873]], dtype=float32)

In [55]:
x_vals

array([[0.63709357, 0.28287258],
       [0.46470388, 0.37693872]])

In [56]:
## Variable
sess = tf.Session()
first_variable = tf.Variable(tf.zeros([2,3]))

In [57]:
sess.run(first_variable.initializer)

In [58]:
second_variable = tf.Variable(tf.zeros_like(first_variable))

In [59]:
sess.run(second_variable.initializer)

In [60]:
tf.__version__

'1.13.1'