In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.13.1'

# Hello World Program in TensorFlow

In [3]:
h = tf.constant("Hello")

In [4]:
w = tf.constant("World")

In [5]:
hw = h + w

In [6]:
hw

<tf.Tensor 'add:0' shape=() dtype=string>

In [7]:
with tf.Session() as sess:
    res = sess.run(hw)

In [8]:
res

b'HelloWorld'

# Graphs, Sessions and Fetches

In [9]:
a = tf.constant(5)
b = tf.constant(7)
c = tf.constant(10)

In [11]:
d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)

In [13]:
with tf.Session() as sess:
    out = sess.run(f)

In [14]:
out

18

In [16]:
tf.get_default_graph()

In [17]:
g = tf.Graph()

In [18]:
g

In [19]:
a = tf.constant(5)

In [20]:
a.graph is tf.get_default_graph()

True

In [21]:
with g.as_default():
    a= tf.constant(77)
    print(a.graph)

# Fetches

In [22]:
a = tf.constant(5)
b = tf.constant(7)
c = tf.constant(10)
d = tf.multiply(a,b)
e = tf.add(b,c)
f = tf.subtract(d,e)
with tf.Session() as sess:
    out = sess.run(f)

In [23]:
with tf.Session() as sess:
    fetches = [a,b,c,d,e,f]
    outs = sess.run(fetches)
    
print(outs)

[5, 7, 10, 35, 17, 18]


# Data Types

In [26]:
c = tf.constant(4.0,dtype=tf.float64)

In [27]:
d = tf.cast(c,tf.float16)

In [28]:
d.dtype

tf.float16

# Tensor Arrays and Shapes

In [24]:
c = tf.constant([[1,2,3],[4,5,6]])

In [25]:
import numpy as np

In [29]:
d = np.array([[1,2,3],[4,5,6]])

In [30]:
tf.constant(d)

<tf.Tensor 'Const_11:0' shape=(2, 3) dtype=int32>

In [31]:
d = tf.linspace(start=2.0, stop=10.0, num=20)

In [32]:
with tf.Session() as sess:
    out = sess.run(d)
out

array([ 2.       ,  2.4210527,  2.8421054,  3.2631578,  3.6842105,
        4.105263 ,  4.5263157,  4.9473686,  5.368421 ,  5.7894735,
        6.2105265,  6.631579 ,  7.0526314,  7.4736843,  7.894737 ,
        8.31579  ,  8.736842 ,  9.157894 ,  9.578947 , 10.       ],
      dtype=float32)

In [33]:
s = tf.fill((4,5),100)

In [35]:
with tf.Session() as sess:
    out = sess.run(s)
out

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [36]:
A = tf.constant([[1,2,3],[4,5,6]])

In [37]:
b = tf.constant([1,0,1])

In [38]:
b = tf.expand_dims(b,1)

In [39]:
b.shape

TensorShape([Dimension(3), Dimension(1)])

In [40]:
A.shape

TensorShape([Dimension(2), Dimension(3)])

In [41]:
matmul = tf.matmul(A,b)

In [42]:
with tf.Session() as sess:
    out = sess.run(matmul)
    
out

array([[ 4],
       [10]])

In [43]:
with tf.Session() as sess:
    fetches = [A,b]
    out = sess.run(fetches)

In [44]:
out

[array([[1, 2, 3],
        [4, 5, 6]]), array([[1],
        [0],
        [1]])]

In [45]:
r = tf.transpose(A)

In [47]:
with tf.Session() as sess:
    out = sess.run(r)
out

array([[1, 4],
       [2, 5],
       [3, 6]])

# VAriables and Place Holders

In [48]:
init_vals = tf.random_normal((1,5),0,1)

In [49]:
init_vals.shape

TensorShape([Dimension(1), Dimension(5)])

In [50]:
var = tf.Variable(init_vals)

Instructions for updating:
Colocations handled automatically by placer.


In [51]:
init = tf.global_variables_initializer()

In [53]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(var))

[[ 0.5005604  -2.1353745   0.25810942  0.19775063 -0.32520437]]


# Placeholders

In [55]:
ph = tf.placeholder(tf.int16)

In [56]:
d = tf.multiply(ph,2)

In [59]:
with tf.Session() as sess:
    print(sess.run(d, feed_dict={ph:5}))
    print(sess.run(d, feed_dict={ph:100}))

10
200
