In [1]:
import tensorflow as tf

# Fixed Tensors

In [2]:
zero_tsr = tf.zeros([4,5])

In [3]:
with tf.Session() as sess:
    print(sess.run(zero_tsr))
    zero_tsr =zero_tsr + 2
    print(sess.run(zero_tsr))
    

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [4]:
type(zero_tsr)

tensorflow.python.framework.ops.Tensor

In [5]:
ones_tsr = tf.ones([3,4])
sess = tf.Session()
sess.run(ones_tsr)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [6]:
fill_tsr = tf.fill([4,5], 1001)
sess.run(fill_tsr)

array([[1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001]])

# Sequence Tensors

In [7]:
lindata = tf.linspace(start=0.0,stop=1.0, num=5)

In [8]:
sess.run(lindata)

array([0.  , 0.25, 0.5 , 0.75, 1.  ], dtype=float32)

In [9]:
rand_tsr = tf.random_normal([4,4])

In [10]:
sess.run(rand_tsr)

array([[-0.7938131 , -0.22781464,  1.1978682 , -0.9825756 ],
       [-0.57499677,  0.76852286,  0.5730805 ,  0.00516525],
       [-1.3467163 , -1.2793798 ,  0.6122307 , -1.8016924 ],
       [ 0.07048989, -0.296337  , -1.2818124 , -0.35234407]],
      dtype=float32)

In [11]:
d = tf.random_shuffle(rand_tsr)

In [12]:
sess.run(d)

array([[-0.48124573,  0.37556487, -0.18533441, -0.7918185 ],
       [ 0.7763964 , -0.35426933,  0.29071832,  0.23442315],
       [ 0.5796175 ,  0.39207128,  0.6536449 ,  0.55132717],
       [ 0.7788312 , -0.03815864,  2.9115777 ,  0.98781574]],
      dtype=float32)

In [13]:
help(tf.random_normal)

Help on function random_normal in module tensorflow.python.ops.random_ops:

random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
    Outputs random values from a normal distribution.
    
    Args:
      shape: A 1-D integer Tensor or Python array. The shape of the output tensor.
      mean: A 0-D Tensor or Python value of type `dtype`. The mean of the normal
        distribution.
      stddev: A 0-D Tensor or Python value of type `dtype`. The standard deviation
        of the normal distribution.
      dtype: The type of the output.
      seed: A Python integer. Used to create a random seed for the distribution.
        See
        `tf.set_random_seed`
        for behavior.
      name: A name for the operation (optional).
    
    Returns:
      A tensor of the specified shape filled with random normal values.



# PlaceHolders and VAriables

In [14]:
my_var = tf.Variable(tf.zeros([4,6]))

Instructions for updating:
Colocations handled automatically by placer.


In [16]:
with tf.Session() as sess:
    sess.run(my_var.initializer)
    print(sess.run(my_var))
    my_var = tf.add(my_var,5)
    print(sess.run(my_var))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [18]:
t = tf.constant([1,2,3])

In [22]:
sess = tf.Session()
sess.run(t)
t = t + 1
sess.run(t)

array([2, 3, 4])

In [23]:
x = tf.placeholder(tf.float32, shape=[2,2])

In [24]:
with tf.Session() as sess:
    print(sess.run(x, feed_dict={x:[[1,1],[9,9]]}))

[[1. 1.]
 [9. 9.]]


In [25]:
tf.get_default_graph()

In [27]:
g =tf.Graph()
g

In [28]:
a = tf.get_default_graph()

In [29]:
a = tf.constant(5)
b = tf.placeholder(tf.int32,shape=[2,2])
c = tf.constant(15)
d = tf.constant(26)
e = tf.constant(25)
f = b + a

In [31]:
with tf.Session() as sess:
    fetches = [a,b,c,d,e,f]
    outs = sess.run(fetches, feed_dict={b:[[4,4],[7,7]]})

In [32]:
outs

[5, array([[4, 4],
        [7, 7]]), 15, 26, 25, array([[ 9,  9],
        [12, 12]])]

In [35]:
a.graph

In [36]:
tf.get_default_graph()